version: "3"
services:
  nest-boilerplate:
    build: .
    hostname: video-touch
    image: video-touch
    container_name: video-touch
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - $PORT:$PORT