version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .mongo/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  video-touch-api:
    image: 578965/video-touch-api
    container_name: video-touch-api
    build: api
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=$API_PORT
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
      - ./uploads:$TEMP_UPLOAD_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

#  download-video-worker:
#    image: 578965/download-video-worker
#    container_name: download-video-worker
#    build: workers/download-video-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - DOWNLOAD_VIDEO_WORKER_PORT=$DOWNLOAD_VIDEO_WORKER_PORT
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.1"
#  validate-video-worker:
#    image: 578965/validate-video-worker
#    container_name: validate-video-worker
#    build: workers/validate-video-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - VALIDATE_VIDEO_WORKER_PORT=$VALIDATE_VIDEO_WORKER_PORT
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.1"
#  thumbnail-generation-worker:
#    image: 578965/thumbnail-generation-worker
#    container_name: thumbnail-generation-worker
#    build: workers/thumbnail-generation-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - THUMBNAIL_WORKER_PORT=$THUMBNAIL_WORKER_PORT
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.1"
#
#  process-video-worker-360p:
#    image: 578965/process-video-worker
#    container_name: process-video-worker-360p
#    build: workers/process-video-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
#      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_360P_PROCESS_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_360p_PROCESS_VIDEO_QUEUE
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_360p_UPLOAD_VIDEO_ROUTING_KEY
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.2"
#  process-video-worker-480p:
#    image: 578965/process-video-worker
#    container_name: process-video-worker-480p
#    build: workers/process-video-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
#      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_480P_PROCESS_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_480p_PROCESS_VIDEO_QUEUE
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_480p_UPLOAD_VIDEO_ROUTING_KEY
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.2"
#
#  process-video-worker-540p:
#    image: 578965/process-video-worker
#    container_name: process-video-worker-540p
#    build: workers/process-video-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
#      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_540P_PROCESS_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_540p_PROCESS_VIDEO_QUEUE
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_540p_UPLOAD_VIDEO_ROUTING_KEY
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.2"
#
#  process-video-worker-720p:
#    image: 578965/process-video-worker
#    container_name: process-video-worker-720p
#    build: workers/process-video-worker
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
#      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_720P_PROCESS_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_720p_PROCESS_VIDEO_QUEUE
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_720p_UPLOAD_VIDEO_ROUTING_KEY
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.2"
#
#
#  upload-video-worker-360p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-360p
#    build:
#      context: workers/upload-video-worker
#      args:
#        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#        AWS_DEFAULT_REGION: $AWS_REGION
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_360p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_360p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.05"
#
#  upload-video-worker-480p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-480p
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    build:
#      context: workers/upload-video-worker
#      args:
#        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#        AWS_DEFAULT_REGION: $AWS_REGION
#    env_file: .env
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_480p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_480p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.05"
#  upload-video-worker-540p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-540p
#    build:
#      context: workers/upload-video-worker
#      args:
#        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#        AWS_DEFAULT_REGION: $AWS_REGION
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_540p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_540p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.05"
#  upload-video-worker-720p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-720p
#    build:
#      context: workers/upload-video-worker
#      args:
#        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#        AWS_DEFAULT_REGION: $AWS_REGION
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_720p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_720p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#      resources:
#        limits:
#          cpus: "0.05"
