version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .mongo/data/db:/data/db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - .docker-conf/redis/data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  video-touch-api:
    image: 578965/video-touch-api
    container_name: video-touch-api
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=$API_PORT
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
      - ./uploads:$TEMP_UPLOAD_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  download-video-worker:
    image: 578965/download-video-worker
    container_name: download-video-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - DOWNLOAD_VIDEO_WORKER_PORT=$DOWNLOAD_VIDEO_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  validate-video-worker:
    image: 578965/validate-video-worker
    container_name: validate-video-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - VALIDATE_VIDEO_WORKER_PORT=$VALIDATE_VIDEO_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  thumbnail-generation-worker:
    image: 578965/thumbnail-generation-worker
    container_name: thumbnail-generation-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - THUMBNAIL_WORKER_PORT=$THUMBNAIL_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  process-video-worker-360p:
    image: 578965/process-video-worker
    container_name: process-video-worker-360p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_360P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "0"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


  process-video-worker-480p:
    image: 578965/process-video-worker
    container_name: process-video-worker-480p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_480P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "1"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3



  process-video-worker-540p:
    image: 578965/process-video-worker
    container_name: process-video-worker-540p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_540P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "2"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


  process-video-worker-720p:
    image: 578965/process-video-worker
    container_name: process-video-worker-720p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_720P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "3"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  upload-video-worker-360p:
    image: 578965/upload-video-worker
    container_name: upload-video-worker-360p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
    environment:
      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


#  upload-video-worker-480p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-480p
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    env_file: .env
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_480p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_480p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#  upload-video-worker-540p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-540p
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_540p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_540p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#
#  upload-video-worker-720p:
#    image: 578965/upload-video-worker
#    container_name: upload-video-worker-720p
#    env_file: .env
#    depends_on:
#      - video-touch-api
#      - rabbitmq
#    environment:
#      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
#      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_720p_UPLOAD_VIDEO_ROUTING_KEY
#      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_720p_UPLOAD_VIDEO_QUEUE
#    volumes:
#      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3