version: "3"
services:
  video-touch-api:
    image: video-touch-api:master-f10eb8d7f
    container_name: video-touch-api
    build: api
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$API_PORT
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
      - ./uploads:$TEMP_UPLOAD_DIRECTORY

  download-video-worker:
    image: download-video-worker
    container_name: download-video-worker
    build: workers/download-video-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - DOWNLOAD_VIDEO_WORKER_PORT=$DOWNLOAD_VIDEO_WORKER_PORT
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
  validate-video-worker:
    image: validate-video-worker
    container_name: validate-video-worker
    build: workers/validate-video-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - VALIDATE_VIDEO_WORKER_PORT=$VALIDATE_VIDEO_WORKER_PORT
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
  process-video-worker-360p:
    image: process-video-worker
    container_name: process-video-worker-360p
    build: workers/process-video-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_360P_PROCESS_VIDEO_ROUTING_KEY
      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_360p_PROCESS_VIDEO_QUEUE
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_360p_UPLOAD_VIDEO_ROUTING_KEY
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "0.5"
        reservations:
          cpus: "0.3"

  process-video-worker-480p:
    image: process-video-worker
    container_name: process-video-worker-480p
    build: workers/process-video-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_480P_PROCESS_VIDEO_ROUTING_KEY
      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_480p_PROCESS_VIDEO_QUEUE
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_480p_UPLOAD_VIDEO_ROUTING_KEY
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "0.5"
        reservations:
          cpus: "0.3"

  process-video-worker-540p:
    image: process-video-worker
    container_name: process-video-worker-540p
    build: workers/process-video-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_540P_PROCESS_VIDEO_ROUTING_KEY
      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_540p_PROCESS_VIDEO_QUEUE
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_540p_UPLOAD_VIDEO_ROUTING_KEY
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "1"
        reservations:
          cpus: "0.5"

  process-video-worker-720p:
    image: process-video-worker
    container_name: process-video-worker-720p
    build: workers/process-video-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - RABBIT_MQ_PROCESS_VIDEO_ROUTING_KEY=$RABBIT_MQ_720P_PROCESS_VIDEO_ROUTING_KEY
      - RABBIT_MQ_PROCESS_VIDEO_QUEUE=$RABBIT_MQ_720p_PROCESS_VIDEO_QUEUE
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_720p_UPLOAD_VIDEO_ROUTING_KEY
    volumes:
      - ~/.aws:/root/.aws
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "1"
        reservations:
          cpus: "0.5"


  upload-video-worker-360p:
    image: upload-video-worker
    container_name: upload-video-worker-360p
    build:
      context: workers/upload-video-worker
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: $AWS_REGION
    restart: unless-stopped
    env_file: .env
    environment:
      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_360p_UPLOAD_VIDEO_ROUTING_KEY
      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_360p_UPLOAD_VIDEO_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "0.2"
        reservations:
          cpus: "0.1"

  upload-video-worker-480p:
    image: upload-video-worker
    container_name: upload-video-worker-480p
    build:
      context: workers/upload-video-worker
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: $AWS_REGION
    restart: unless-stopped
    env_file: .env
    environment:
      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_480p_UPLOAD_VIDEO_ROUTING_KEY
      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_480p_UPLOAD_VIDEO_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "0.2"
        reservations:
          cpus: "0.1"
  upload-video-worker-540p:
    image: upload-video-worker
    container_name: upload-video-worker-540p
    build:
      context: workers/upload-video-worker
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: $AWS_REGION
    restart: unless-stopped
    env_file: .env
    environment:
      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_540p_UPLOAD_VIDEO_ROUTING_KEY
      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_540p_UPLOAD_VIDEO_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "0.5"
        reservations:
          cpus: "0.3"
  upload-video-worker-720p:
    image: upload-video-worker
    container_name: upload-video-worker-720p
    build:
      context: workers/upload-video-worker
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: $AWS_REGION
    restart: unless-stopped
    env_file: .env
    environment:
      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
      - RABBIT_MQ_UPLOAD_VIDEO_ROUTING_KEY=$RABBIT_MQ_720p_UPLOAD_VIDEO_ROUTING_KEY
      - RABBIT_MQ_UPLOAD_VIDEO_QUEUE=$RABBIT_MQ_720p_UPLOAD_VIDEO_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      resources:
        limits:
          cpus: "1"
        reservations:
          cpus: "0.5"