version: "3.7"
services:
  video-touch-api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: video-touch-api
    env_file: .env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PORT=$API_PORT
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
      - ./uploads:$TEMP_UPLOAD_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  download-video-worker:
    build:
      context: workers/download-video-worker
      dockerfile: Dockerfile
    container_name: download-video-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - DOWNLOAD_VIDEO_WORKER_PORT=$DOWNLOAD_VIDEO_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  validate-video-worker:
    build:
      context: workers/validate-video-worker
      dockerfile: Dockerfile
    container_name: validate-video-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - VALIDATE_VIDEO_WORKER_PORT=$VALIDATE_VIDEO_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  thumbnail-generation-worker:
    build:
      context: workers/thumbnail-generation-worker
      dockerfile: Dockerfile
    container_name: thumbnail-generation-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - THUMBNAIL_WORKER_PORT=$THUMBNAIL_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  process-video-worker-360p:
    build:
      context: workers/process-video-worker
      dockerfile: Dockerfile
    container_name: process-video-worker-360p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_360P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "0-3"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


  process-video-worker-480p:
    build:
      context: workers/process-video-worker
      dockerfile: Dockerfile
    container_name: process-video-worker-480p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_480P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "4-7"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  process-video-worker-720p:
    build:
      context: workers/process-video-worker
      dockerfile: Dockerfile
    container_name: process-video-worker-720p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_720P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "8-11"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  process-video-worker-1080p:
    build:
      context: workers/process-video-worker
      dockerfile: Dockerfile
    container_name: process-video-worker-1080p
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - PROCESS_VIDEO_WORKER_PORT=$PROCESS_VIDEO_WORKER_PORT
      - BULL_PROCESS_VIDEO_JOB_QUEUE=$BULL_1080P_PROCESS_VIDEO_JOB_QUEUE
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    cpuset: "8-11"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


  upload-video-worker:
    build:
      context: workers/upload-video-worker
      dockerfile: Dockerfile
    container_name: upload-video-worker
    env_file: .env
    depends_on:
      - video-touch-api
      - rabbitmq
      - redis
    environment:
      - UPLOAD_VIDEO_WORKER_PORT=$UPLOAD_VIDEO_WORKER_PORT
    volumes:
      - ./temp_videos:$TEMP_VIDEO_DIRECTORY
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3