name: Build and publish Upload Video Worker docker image
on:
  push:
    branches:
      - master
    paths:
      - server/workers/upload-video-worker/**
jobs:
  setup-build-publish:
    name: Setup, Build, and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: worker build and push to registry
        uses: docker/build-push-action@v3
        with:
          context: ./server/workers/upload-video-worker
          file: ./server/workers/upload-video-worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/upload-video-worker:latest
